### ISSUE TITLE
Bulwark-Decision header should incorporate score and outcome values

### ISSUE THREAD

**Issue by sporkmonger** [bulwark-security/bulwark#108]
Currently a header value looks like this:
```
Bulwark-Decision: accept=0.0, restrict=0.55, unknown=0.45
```
This could be challenging for anyone ingesting it who is not already well-verse in Dempster-Shafer Theory to do anything practical with. It would be better to include the threshold information and risk score like we do in the logs:
```
Bulwark-Decision: accept=0.0, restrict=0.55, unknown=0.45, score=0.775, outcome=suspected
```

**Comment by malizz** [comment]
PR: https://github.com/bulwark-security/bulwark/pull/125 implemented this feature.
