### ISSUE TITLE
File not found errors don't indicate the filename

### ISSUE THREAD

**Issue by sporkmonger** [bulwark-security/bulwark#25]
This shows up throughout the `bulwark-config` crate and makes understanding some errors particularly difficult. This can happen in a number of scenarios:

- when a config file doesn't exist
- when an include path within a config file doesn't exist
- when a plugin .wasm path within a config file doesn't exist

All of these scenarios should indicate the file name that was attempted. An additional improvement would be to indicate the exact location in the config file where the incorrect file name occurred.

**Comment by kadinsayani** [comment]
Hi, I'd like to tackle this issue. If possible, can you please provide steps to reproduce some of these errors?

**Comment by sporkmonger** [comment]
Hey Kadin, sorry about the slow reply! You should be able to reproduce most easily by specifying a bogus config file, e.g. `bulwark-cli ext-processor --config=doesnotexist.toml`, however the issue covers essentially all the scenarios listed above, not just that one.

**Comment by sporkmonger** [comment]
This should probably get some explicit test cases as well. Should be relatively straightforward to test for.

**Comment by kadinsayani** [comment]
Hi! Can you please add the PR I just opened to the issue? Thanks!
